apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-service
  namespace: ml-demo
  labels:
    app: deploy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-service
  template:
    metadata:
      labels:
        app: deploy-service
    spec:
      serviceAccountName: deploy-service
      automountServiceAccountToken: True
      containers:
      - name: deploy-service
        image: deploy-service:1
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-service
  namespace: ml-demo
spec:
  selector:
    app: deploy-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deploy-service
  namespace: ml-demo
  labels:
    app: deploy-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - host: dev.xgboostdemo.com
      http:
        paths:
          - backend:
              service:
                name: deploy-service
                port:
                  number: 80
            path: /deploy-service
            pathType: Prefix